pipeline 
               {
                   agent any    
                   tools
                   {
                     maven 'maven'
                     nodejs 'node'
                   }
                   stages 
                    {
                      stage('First stage') 
                      {
                       steps 
                        {
                         println "Hello World"
                         sh ''' 
                         mvn -version
                         node --version
                         npm --version
                         '''
                        }
                      }
                        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
                    }
               }
